language: php
os: linux
dist: xenial

matrix:
  include:
    - php: 5.6
      env: VERSIONS=--prefer-lowest
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - travis_retry composer update $VERSIONS

script:
  - vendor/bin/phpunit tests
